id: PA696A47D
initial_creation_type: ocr
source_metadata:
  volumes:
    4276c7fa4cef45aea0a4e8d5a904e10f:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: ཕུང་པོ་ལྔའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1517
      volume_number: 77
